const ORIGINAL_URL='https://raw.githubusercontent.com/implantarhconsultoria-coder/implantarh-primeflow/7d6642e94531cc7d8611ad9913a60c8237aab8bc/index.html';
const state={view:'home',step:1,nome:'',contato:'',empresas:'',filiais:'',funcionarios:'',versao:'',instalacao:'',dominio:'',dadosDominio:'',suporte:'',esocial:'',eventos:'',backup:'',matriculas:'',folha:[],historico:[],ultima:'',desejada:'',amostra:'',obs:'',protocolo:''};
const FOLHA=['Rubricas personalizadas','Horas extras','Comissões','Insalubridade/periculosidade','Pensão alimentícia','Empréstimos/consignados','Benefícios em folha','Adiantamento salarial','Férias em andamento','Médias de férias/13º','Vários sindicatos'];
const HIST=['Holerites antigos','Recibos de férias e rescisões','Bases de INSS/FGTS/IRRF','Ficha financeira','Histórico de salários/cargos','12 meses ou mais de histórico'];
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function saveDraft(){try{localStorage.setItem('primeflow-draft-v2',JSON.stringify(state))}catch(e){}}
function loadDraft(){try{const d=JSON.parse(localStorage.getItem('primeflow-draft-v2')||'null');if(d&&typeof d==='object'){Object.assign(state,d);state.view='home';state.step=Math.max(1,Number(state.step)||1)}}catch(e){}}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function setView(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='diagnostic')render();saveDraft()}
function maskPhone(v){v=v.replace(/\D/g,'').slice(0,11);if(v.length<=2)return v;if(v.length<=6)return `(${v.slice(0,2)}) ${v.slice(2)}`;if(v.length<=10)return `(${v.slice(0,2)}) ${v.slice(2,6)}-${v.slice(6)}`;return `(${v.slice(0,2)}) ${v.slice(2,7)}-${v.slice(7)}`}
function chips(name,options,current,cols){return `<div class="choices ${cols||''}">${options.map(o=>`<button type="button" class="chip ${current===o?'on':''}" data-name="${name}" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div>`}
function checks(name,options,current){const set=new Set(current);return `<div class="choices">${options.map(o=>`<button type="button" class="check ${set.has(o)?'on':''}" data-multi="${name}" data-value="${esc(o)}">${set.has(o)?'☑':'☐'} ${esc(o)}</button>`).join('')}</div>`}
function screenHTML(){
 if(state.step===1)return `<h1>Estrutura Atual</h1><p class="lead">Vamos dimensionar o ambiente que será migrado.</p><label class="fld">Quantas empresas/CNPJs?</label><div class="input"><input id="empresas" placeholder="Exemplo: 18" value="${esc(state.empresas)}"></div><label class="fld">Quantas filiais?</label><div class="input"><input id="filiais" placeholder="Exemplo: 4" value="${esc(state.filiais)}"></div><label class="fld">Funcionários aproximadamente</label><div class="input"><input id="funcionarios" placeholder="Exemplo: 650" value="${esc(state.funcionarios)}"></div><label class="fld">Versão do Contmatic</label><div class="input"><input id="versao" placeholder="Informe a versão" value="${esc(state.versao)}"></div><label class="fld">Onde o Contmatic está instalado?</label>${chips('instalacao',['Servidor local','Nuvem','Computador/estação','Não sei informar'],state.instalacao)}<div class="err" id="err"></div><div class="actions"><button class="btn ghost" id="back">← VOLTAR</button><button class="btn primary" id="next">CONTINUAR →</button></div>`;
 if(state.step===2)return `<h1>Sistemas e Situação Atual</h1><p class="lead">Precisamos entender onde os dados estão e o que já existe no Domínio.</p><label class="fld">O Domínio já está disponível?</label>${chips('dominio',['Contratado e funcionando','Contratado, implantação pendente','Ainda não contratado'],state.dominio)}<label class="fld">Já existem dados/funcionários no Domínio?</label>${chips('dadosDominio',['Sim','Não','Não sei informar'],state.dadosDominio,'three')}<label class="fld">Existe acompanhamento do suporte Domínio?</label>${chips('suporte',['Sim','Não','Ainda será solicitado'],state.suporte,'three')}<label class="fld">Como está o eSocial hoje?</label>${chips('esocial',['Regular','Possui pendências','Precisa verificar'],state.esocial,'three')}<label class="fld">Existem eventos pendentes no eSocial?</label>${chips('eventos',['Não','Sim','Não sei informar'],state.eventos,'three')}<label class="fld">Conseguem gerar backup completo do Contmatic?</label>${chips('backup',['Sim','Não','Precisa verificar'],state.backup,'three')}<label class="fld">Precisamos preservar as matrículas atuais?</label>${chips('matriculas',['Sim','Não','Precisa validar'],state.matriculas,'three')}<div class="err" id="err"></div><div class="actions"><button class="btn ghost" id="back">← VOLTAR</button><button class="btn primary" id="next">CONTINUAR →</button></div>`;
 if(state.step===3)return `<h1>Complexidade da Folha</h1><p class="lead">Marque tudo que faz parte da operação atual.</p><div class="group-title">ITENS EXISTENTES NA FOLHA</div>${checks('folha',FOLHA,state.folha)}<div class="group-title">HISTÓRICO QUE PRECISA PERMANECER ACESSÍVEL</div>${checks('historico',HIST,state.historico)}<div class="err" id="err"></div><div class="actions"><button class="btn ghost" id="back">← VOLTAR</button><button class="btn primary" id="next">CONTINUAR →</button></div>`;
 if(state.step===4)return `<h1>Virada e Documentação</h1><p class="lead">Essas respostas definem o ponto de corte do projeto.</p><label class="fld">Última competência fechada no Contmatic</label><div class="input"><input id="ultima" placeholder="Exemplo: 09/2026" value="${esc(state.ultima)}"></div><label class="fld">Competência desejada para iniciar no Domínio</label><div class="input"><input id="desejada" placeholder="Exemplo: 10/2026" value="${esc(state.desejada)}"></div><label class="fld">Consegue enviar uma folha analítica + relação de funcionários de uma empresa como amostra?</label>${chips('amostra',['Sim','Não','Precisa verificar'],state.amostra,'three')}<label class="fld">Observações importantes</label><div class="input"><textarea id="obs" placeholder="Ex.: férias em andamento, desligamentos recentes, urgência da virada...">${esc(state.obs)}</textarea></div><div class="err" id="err"></div><div class="actions"><button class="btn ghost" id="back">← VOLTAR</button><button class="btn primary" id="next">FINALIZAR DIAGNÓSTICO →</button></div>`;
 return `<div class="done-kicker">DIAGNÓSTICO RECEBIDO</div><h1>Informações registradas<br>com sucesso.</h1><p class="lead">O material será usado para definir a rota mais segura da migração Contmatic → Domínio.</p><div class="protocol"><small>PROTOCOLO PRIMEFLOW</small><strong>${esc(state.protocolo)}</strong><button class="btn ghost" id="copy" type="button">Copiar protocolo</button></div><div class="mini-cards"><div class="mini"><b>DADOS ORGANIZADOS</b><span>Escopo centralizado para análise.</span></div><div class="mini"><b>PRÓXIMA ETAPA</b><span>Mapeamento técnico e plano de virada.</span></div><div class="mini"><b>VALIDAÇÃO</b><span>Conferência antes de qualquer alteração.</span></div></div><div class="actions"><button class="btn ghost" id="back">← VOLTAR</button><button class="btn primary" id="save">SALVAR DIAGNÓSTICO</button></div>`;
}
function readFields(){const root=document.getElementById('screen');['empresas','filiais','funcionarios','versao','ultima','desejada','obs'].forEach(k=>{const el=root.querySelector('#'+k);if(el)state[k]=el.value.trim()})}
function validate(){if(state.step===1&&(!state.empresas||!state.filiais||!state.funcionarios||!state.versao||!state.instalacao))return 'Preencha empresas, filiais, funcionários, versão e onde o Contmatic está instalado.';if(state.step===2&&['dominio','dadosDominio','suporte','esocial','eventos','backup','matriculas'].some(k=>!state[k]))return 'Responda todas as perguntas desta etapa.';if(state.step===4&&(!state.ultima||!state.desejada||!state.amostra))return 'Informe as competências e a disponibilidade da amostra.';return ''}
function sideHTML(){const pct=state.step>=5?100:Math.round(((state.step-1)/4)*100);const func=Number(String(state.funcionarios).replace(/\D/g,''))||0;const days=func>800?32:func>300?24:func>0?16:18;const label=['','Estrutura Atual','Sistemas e Situação','Complexidade da Folha','Virada e Documentação','Finalizado'][state.step];return `<div class="side-block"><small>SISTEMA</small><strong><span style="color:#34d399">●</span> Operacional</strong></div><div class="side-block"><small>ETAPA ATUAL</small><strong>${esc(label)}</strong></div><div class="side-block"><small>PROGRESSO</small><strong>${pct}%</strong><div class="progress"><span style="width:${pct}%"></span></div></div><div class="side-block"><small>TEMPO ESTIMADO</small><strong>${days} dias</strong></div>`}
function render(){document.getElementById('userName').textContent=state.nome||'—';document.querySelectorAll('.step-tab').forEach(el=>{const n=+el.dataset.step;el.classList.toggle('on',state.step===n);el.classList.toggle('done',state.step>n)});document.getElementById('screen').innerHTML=screenHTML();document.getElementById('sidePanel').innerHTML=sideHTML();bindScreen();saveDraft()}
function bindScreen(){const root=document.getElementById('screen');root.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state[b.dataset.name]=b.dataset.value;render()});root.querySelectorAll('.check').forEach(b=>b.onclick=()=>{const key=b.dataset.multi,v=b.dataset.value,arr=new Set(state[key]);arr.has(v)?arr.delete(v):arr.add(v);state[key]=[...arr];render()});const next=root.querySelector('#next'),back=root.querySelector('#back');if(next)next.onclick=()=>{readFields();const msg=validate();if(msg){const e=root.querySelector('#err');if(e)e.textContent=msg;return}if(state.step===4&&!state.protocolo)state.protocolo='PRIME-2026-'+Math.random().toString(16).slice(2,10).toUpperCase();state.step=Math.min(5,state.step+1);render();window.scrollTo({top:0,behavior:'smooth'})};if(back)back.onclick=()=>{readFields();if(state.step===1){setView('access');return}state.step=Math.max(1,state.step-1);render();window.scrollTo({top:0,behavior:'smooth'})};const copy=root.querySelector('#copy');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(state.protocolo);toast('Protocolo copiado.')}catch{toast(state.protocolo)}};const save=root.querySelector('#save');if(save)save.onclick=()=>{const blob=new Blob([JSON.stringify({produto:'ImplantaRH PrimeFlow',protocolo:state.protocolo,respostas:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.protocolo||'primeflow')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Diagnóstico salvo.')};root.querySelectorAll('input,textarea').forEach(el=>el.addEventListener('input',()=>{const e=root.querySelector('#err');if(e)e.textContent=''}))}
async function loadOriginalAssets(){try{const r=await fetch(ORIGINAL_URL,{cache:'force-cache'});if(!r.ok)return;const html=await r.text();const bg=html.match(/background:\s*url\(\"(data:image\/jpeg;base64,[^\"]+)\"\)/);const logo=html.match(/src=\"(data:image\/png;base64,[^\"]+)\"/);if(bg){const c=document.getElementById('homeCanvas');c.style.backgroundImage=`url("${bg[1]}")`;c.classList.add('has-bg');const fb=c.querySelector('.home-fallback');if(fb)fb.style.display='none'}if(logo){document.querySelectorAll('.shared-logo').forEach(i=>{i.src=logo[1];i.style.display='block'})}}catch(e){}}
loadDraft();document.getElementById('accessName').value=state.nome||'';document.getElementById('accessPhone').value=state.contato||'';document.getElementById('homeAccess').onclick=()=>setView('access');document.getElementById('backHome').onclick=()=>setView('home');document.getElementById('accessPhone').addEventListener('input',e=>{e.target.value=maskPhone(e.target.value);document.getElementById('accessErr').textContent=''});document.getElementById('accessName').addEventListener('input',()=>document.getElementById('accessErr').textContent='');document.getElementById('enterDiagnostic').onclick=()=>{const nome=document.getElementById('accessName').value.trim();const phone=document.getElementById('accessPhone').value.trim();const digits=phone.replace(/\D/g,'');if(nome.length<3){document.getElementById('accessErr').textContent='Informe seu nome completo.';return}if(digits.length<10){document.getElementById('accessErr').textContent='Informe um WhatsApp/telefone válido.';return}state.nome=nome;state.contato=phone;state.step=Math.max(1,state.step||1);setView('diagnostic')};loadOriginalAssets();
